server:
  port: ${CABIN_SERVER_PORT:18030}
  servlet:
    encoding:
      force: true
      charset: UTF-8
ws:
#  host: ${CABIN_WS_HOST:0.0.0.0}
  port1: ${LINE_WS_PORT:18080}
  port2: ${OBS_WS_PORT:18081}
  port3: ${POTION_WS_PORT:18082}
  port4: ${SPEED_WS_PORT:18083}
  point:
    port1: ${POINT_CLOUND_WS_PORT:18180}
    port2: ${POINT_OBS_WS_PORT:18181}
    port3: ${POINT_POSITION_WS_PORT:18182}
  render:
    port1: ${COLLECT_DETAIL_WS_PORT:18280}

#spring:
#  redis:
#    host: ${REDIS_HOST:127.0.0.1}
#    port: ${REDIS_PORT:6379}
#    password: ${REDIS_PASSWORD:}
#    database: ${REDIS_DATABASE:0}
  datasource:
    url: jdbc:postgresql://172.16.107.102:30652/cabin?characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&serverTimezone=Asia/Shanghai&useAffectedRows=true
    username: postgres
    password: password

#数据库配置
#spring:
#  datasource:
#    url: jdbc:mysql://127.0.0.1:9966/study?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&autoReconnect=true&useSSL=false&verifyServerCertificate=false
#    username: root
#    password: 123456
#    # 使用druid数据源
#    driver-class-name: com.mysql.jdbc.Driver
