// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dpi_me_output.proto

package com.dpi.map.cabin.domain.proto;

public final class DpiMeOutput {
  private DpiMeOutput() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CPoint6DOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.dpi.map.cabin.domain.proto.CPoint6D)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *&#47;&lt; x坐标
     * </pre>
     *
     * <code>double x = 1;</code>
     * @return The x.
     */
    double getX();

    /**
     * <pre>
     *&#47;&lt; y坐标
     * </pre>
     *
     * <code>double y = 2;</code>
     * @return The y.
     */
    double getY();

    /**
     * <pre>
     *&#47;&lt; z坐标
     * </pre>
     *
     * <code>double z = 3;</code>
     * @return The z.
     */
    double getZ();

    /**
     * <pre>
     *&#47;&lt; 偏航角 ,rad
     * </pre>
     *
     * <code>float yaw = 4;</code>
     * @return The yaw.
     */
    float getYaw();

    /**
     * <pre>
     *&#47;&lt; 俯仰角  ,rad
     * </pre>
     *
     * <code>float pitch = 5;</code>
     * @return The pitch.
     */
    float getPitch();

    /**
     * <pre>
     *&#47;&lt; 横滚角,rad
     * </pre>
     *
     * <code>float roll = 6;</code>
     * @return The roll.
     */
    float getRoll();
  }
  /**
   * <pre>
   **
   * &#64;brief 6轴坐标点，在三轴位姿（xyz）的基础上，增加了三轴位姿（横滚角、俯仰角、偏航角）
   * </pre>
   *
   * Protobuf type {@code com.dpi.map.cabin.domain.proto.CPoint6D}
   */
  public static final class CPoint6D extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.dpi.map.cabin.domain.proto.CPoint6D)
      CPoint6DOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CPoint6D.newBuilder() to construct.
    private CPoint6D(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CPoint6D() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new CPoint6D();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CPoint6D(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {

              x_ = input.readDouble();
              break;
            }
            case 17: {

              y_ = input.readDouble();
              break;
            }
            case 25: {

              z_ = input.readDouble();
              break;
            }
            case 37: {

              yaw_ = input.readFloat();
              break;
            }
            case 45: {

              pitch_ = input.readFloat();
              break;
            }
            case 53: {

              roll_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dpi.map.cabin.domain.proto.DpiMeOutput.internal_static_dpi_comm_mapengine_CPoint6D_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dpi.map.cabin.domain.proto.DpiMeOutput.internal_static_dpi_comm_mapengine_CPoint6D_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dpi.map.cabin.domain.proto.DpiMeOutput.CPoint6D.class, com.dpi.map.cabin.domain.proto.DpiMeOutput.CPoint6D.Builder.class);
    }

    public static final int X_FIELD_NUMBER = 1;
    private double x_;
    /**
     * <pre>
     *&#47;&lt; x坐标
     * </pre>
     *
     * <code>double x = 1;</code>
     * @return The x.
     */
    @Override
    public double getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 2;
    private double y_;
    /**
     * <pre>
     *&#47;&lt; y坐标
     * </pre>
     *
     * <code>double y = 2;</code>
     * @return The y.
     */
    @Override
    public double getY() {
      return y_;
    }

    public static final int Z_FIELD_NUMBER = 3;
    private double z_;
    /**
     * <pre>
     *&#47;&lt; z坐标
     * </pre>
     *
     * <code>double z = 3;</code>
     * @return The z.
     */
    @Override
    public double getZ() {
      return z_;
    }

    public static final int YAW_FIELD_NUMBER = 4;
    private float yaw_;
    /**
     * <pre>
     *&#47;&lt; 偏航角 ,rad
     * </pre>
     *
     * <code>float yaw = 4;</code>
     * @return The yaw.
     */
    @Override
    public float getYaw() {
      return yaw_;
    }

    public static final int PITCH_FIELD_NUMBER = 5;
    private float pitch_;
    /**
     * <pre>
     *&#47;&lt; 俯仰角  ,rad
     * </pre>
     *
     * <code>float pitch = 5;</code>
     * @return The pitch.
     */
    @Override
    public float getPitch() {
      return pitch_;
    }

    public static final int ROLL_FIELD_NUMBER = 6;
    private float roll_;
    /**
     * <pre>
     *&#47;&lt; 横滚角,rad
     * </pre>
     *
     * <code>float roll = 6;</code>
     * @return The roll.
     */
    @Override
    public float getRoll() {
      return roll_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (x_ != 0D) {
        output.writeDouble(1, x_);
      }
      if (y_ != 0D) {
        output.writeDouble(2, y_);
      }
      if (z_ != 0D) {
        output.writeDouble(3, z_);
      }
      if (yaw_ != 0F) {
        output.writeFloat(4, yaw_);
      }
      if (pitch_ != 0F) {
        output.writeFloat(5, pitch_);
      }
      if (roll_ != 0F) {
        output.writeFloat(6, roll_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (x_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, x_);
      }
      if (y_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, y_);
      }
      if (z_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, z_);
      }
      if (yaw_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, yaw_);
      }
      if (pitch_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, pitch_);
      }
      if (roll_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(6, roll_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.dpi.map.cabin.domain.proto.DpiMeOutput.CPoint6D)) {
        return super.equals(obj);
      }
      com.dpi.map.cabin.domain.proto.DpiMeOutput.CPoint6D other = (com.dpi.map.cabin.domain.proto.DpiMeOutput.CPoint6D) obj;

      if (Double.doubleToLongBits(getX())
          != Double.doubleToLongBits(
              other.getX())) return false;
      if (Double.doubleToLongBits(getY())
          != Double.doubleToLongBits(
              other.getY())) return false;
      if (Double.doubleToLongBits(getZ())
          != Double.doubleToLongBits(
              other.getZ())) return false;
      if (Float.floatToIntBits(getYaw())
          != Float.floatToIntBits(
              other.getYaw())) return false;
      if (Float.floatToIntBits(getPitch())
          != Float.floatToIntBits(
              other.getPitch())) return false;
      if (Float.floatToIntBits(getRoll())
          != Float.floatToIntBits(
              other.getRoll())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + X_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getX()));
      hash = (37 * hash) + Y_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getY()));
      hash = (37 * hash) + Z_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getZ()));
      hash = (37 * hash) + YAW_FIELD_NUMBER;
      hash = (53 * hash) + Float.floatToIntBits(
          getYaw());
      hash = (37 * hash) + PITCH_FIELD_NUMBER;
      hash = (53 * hash) + Float.floatToIntBits(
          getPitch());
      hash = (37 * hash) + ROLL_FIELD_NUMBER;
      hash = (53 * hash) + Float.floatToIntBits(
          getRoll());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.dpi.map.cabin.domain.proto.DpiMeOutput.CPoint6D parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dpi.map.cabin.domain.proto.DpiMeOutput.CPoint6D parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dpi.map.cabin.domain.proto.DpiMeOutput.CPoint6D parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dpi.map.cabin.domain.proto.DpiMeOutput.CPoint6D parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dpi.map.cabin.domain.proto.DpiMeOutput.CPoint6D parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dpi.map.cabin.domain.proto.DpiMeOutput.CPoint6D parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dpi.map.cabin.domain.proto.DpiMeOutput.CPoint6D parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dpi.map.cabin.domain.proto.DpiMeOutput.CPoint6D parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dpi.map.cabin.domain.proto.DpiMeOutput.CPoint6D parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.dpi.map.cabin.domain.proto.DpiMeOutput.CPoint6D parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dpi.map.cabin.domain.proto.DpiMeOutput.CPoint6D parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dpi.map.cabin.domain.proto.DpiMeOutput.CPoint6D parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.dpi.map.cabin.domain.proto.DpiMeOutput.CPoint6D prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     **
     * &#64;brief 6轴坐标点，在三轴位姿（xyz）的基础上，增加了三轴位姿（横滚角、俯仰角、偏航角）
     * </pre>
     *
     * Protobuf type {@code com.dpi.map.cabin.domain.proto.CPoint6D}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.dpi.map.cabin.domain.proto.CPoint6D)
        com.dpi.map.cabin.domain.proto.DpiMeOutput.CPoint6DOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dpi.map.cabin.domain.proto.DpiMeOutput.internal_static_dpi_comm_mapengine_CPoint6D_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dpi.map.cabin.domain.proto.DpiMeOutput.internal_static_dpi_comm_mapengine_CPoint6D_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.dpi.map.cabin.domain.proto.DpiMeOutput.CPoint6D.class, com.dpi.map.cabin.domain.proto.DpiMeOutput.CPoint6D.Builder.class);
      }

      // Construct using com.dpi.map.cabin.domain.proto.DpiMeOutput.CPoint6D.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        x_ = 0D;

        y_ = 0D;

        z_ = 0D;

        yaw_ = 0F;

        pitch_ = 0F;

        roll_ = 0F;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dpi.map.cabin.domain.proto.DpiMeOutput.internal_static_dpi_comm_mapengine_CPoint6D_descriptor;
      }

      @Override
      public com.dpi.map.cabin.domain.proto.DpiMeOutput.CPoint6D getDefaultInstanceForType() {
        return com.dpi.map.cabin.domain.proto.DpiMeOutput.CPoint6D.getDefaultInstance();
      }

      @Override
      public com.dpi.map.cabin.domain.proto.DpiMeOutput.CPoint6D build() {
        com.dpi.map.cabin.domain.proto.DpiMeOutput.CPoint6D result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public com.dpi.map.cabin.domain.proto.DpiMeOutput.CPoint6D buildPartial() {
        com.dpi.map.cabin.domain.proto.DpiMeOutput.CPoint6D result = new com.dpi.map.cabin.domain.proto.DpiMeOutput.CPoint6D(this);
        result.x_ = x_;
        result.y_ = y_;
        result.z_ = z_;
        result.yaw_ = yaw_;
        result.pitch_ = pitch_;
        result.roll_ = roll_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dpi.map.cabin.domain.proto.DpiMeOutput.CPoint6D) {
          return mergeFrom((com.dpi.map.cabin.domain.proto.DpiMeOutput.CPoint6D)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.dpi.map.cabin.domain.proto.DpiMeOutput.CPoint6D other) {
        if (other == com.dpi.map.cabin.domain.proto.DpiMeOutput.CPoint6D.getDefaultInstance()) return this;
        if (other.getX() != 0D) {
          setX(other.getX());
        }
        if (other.getY() != 0D) {
          setY(other.getY());
        }
        if (other.getZ() != 0D) {
          setZ(other.getZ());
        }
        if (other.getYaw() != 0F) {
          setYaw(other.getYaw());
        }
        if (other.getPitch() != 0F) {
          setPitch(other.getPitch());
        }
        if (other.getRoll() != 0F) {
          setRoll(other.getRoll());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.dpi.map.cabin.domain.proto.DpiMeOutput.CPoint6D parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.dpi.map.cabin.domain.proto.DpiMeOutput.CPoint6D) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private double x_ ;
      /**
       * <pre>
       *&#47;&lt; x坐标
       * </pre>
       *
       * <code>double x = 1;</code>
       * @return The x.
       */
      @Override
      public double getX() {
        return x_;
      }
      /**
       * <pre>
       *&#47;&lt; x坐标
       * </pre>
       *
       * <code>double x = 1;</code>
       * @param value The x to set.
       * @return This builder for chaining.
       */
      public Builder setX(double value) {
        
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *&#47;&lt; x坐标
       * </pre>
       *
       * <code>double x = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearX() {
        
        x_ = 0D;
        onChanged();
        return this;
      }

      private double y_ ;
      /**
       * <pre>
       *&#47;&lt; y坐标
       * </pre>
       *
       * <code>double y = 2;</code>
       * @return The y.
       */
      @Override
      public double getY() {
        return y_;
      }
      /**
       * <pre>
       *&#47;&lt; y坐标
       * </pre>
       *
       * <code>double y = 2;</code>
       * @param value The y to set.
       * @return This builder for chaining.
       */
      public Builder setY(double value) {
        
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *&#47;&lt; y坐标
       * </pre>
       *
       * <code>double y = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearY() {
        
        y_ = 0D;
        onChanged();
        return this;
      }

      private double z_ ;
      /**
       * <pre>
       *&#47;&lt; z坐标
       * </pre>
       *
       * <code>double z = 3;</code>
       * @return The z.
       */
      @Override
      public double getZ() {
        return z_;
      }
      /**
       * <pre>
       *&#47;&lt; z坐标
       * </pre>
       *
       * <code>double z = 3;</code>
       * @param value The z to set.
       * @return This builder for chaining.
       */
      public Builder setZ(double value) {
        
        z_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *&#47;&lt; z坐标
       * </pre>
       *
       * <code>double z = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearZ() {
        
        z_ = 0D;
        onChanged();
        return this;
      }

      private float yaw_ ;
      /**
       * <pre>
       *&#47;&lt; 偏航角 ,rad
       * </pre>
       *
       * <code>float yaw = 4;</code>
       * @return The yaw.
       */
      @Override
      public float getYaw() {
        return yaw_;
      }
      /**
       * <pre>
       *&#47;&lt; 偏航角 ,rad
       * </pre>
       *
       * <code>float yaw = 4;</code>
       * @param value The yaw to set.
       * @return This builder for chaining.
       */
      public Builder setYaw(float value) {
        
        yaw_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *&#47;&lt; 偏航角 ,rad
       * </pre>
       *
       * <code>float yaw = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearYaw() {
        
        yaw_ = 0F;
        onChanged();
        return this;
      }

      private float pitch_ ;
      /**
       * <pre>
       *&#47;&lt; 俯仰角  ,rad
       * </pre>
       *
       * <code>float pitch = 5;</code>
       * @return The pitch.
       */
      @Override
      public float getPitch() {
        return pitch_;
      }
      /**
       * <pre>
       *&#47;&lt; 俯仰角  ,rad
       * </pre>
       *
       * <code>float pitch = 5;</code>
       * @param value The pitch to set.
       * @return This builder for chaining.
       */
      public Builder setPitch(float value) {
        
        pitch_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *&#47;&lt; 俯仰角  ,rad
       * </pre>
       *
       * <code>float pitch = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearPitch() {
        
        pitch_ = 0F;
        onChanged();
        return this;
      }

      private float roll_ ;
      /**
       * <pre>
       *&#47;&lt; 横滚角,rad
       * </pre>
       *
       * <code>float roll = 6;</code>
       * @return The roll.
       */
      @Override
      public float getRoll() {
        return roll_;
      }
      /**
       * <pre>
       *&#47;&lt; 横滚角,rad
       * </pre>
       *
       * <code>float roll = 6;</code>
       * @param value The roll to set.
       * @return This builder for chaining.
       */
      public Builder setRoll(float value) {
        
        roll_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *&#47;&lt; 横滚角,rad
       * </pre>
       *
       * <code>float roll = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearRoll() {
        
        roll_ = 0F;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.dpi.map.cabin.domain.proto.CPoint6D)
    }

    // @@protoc_insertion_point(class_scope:com.dpi.map.cabin.domain.proto.CPoint6D)
    private static final com.dpi.map.cabin.domain.proto.DpiMeOutput.CPoint6D DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.dpi.map.cabin.domain.proto.DpiMeOutput.CPoint6D();
    }

    public static com.dpi.map.cabin.domain.proto.DpiMeOutput.CPoint6D getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CPoint6D>
        PARSER = new com.google.protobuf.AbstractParser<CPoint6D>() {
      @Override
      public CPoint6D parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CPoint6D(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CPoint6D> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<CPoint6D> getParserForType() {
      return PARSER;
    }

    @Override
    public com.dpi.map.cabin.domain.proto.DpiMeOutput.CPoint6D getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PositionMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.dpi.map.cabin.domain.proto.PositionMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *&#47;&lt; 消息id
     * </pre>
     *
     * <code>uint32 msgId = 1;</code>
     * @return The msgId.
     */
    int getMsgId();

    /**
     * <pre>
     *&#47;&lt; 消息类型
     * </pre>
     *
     * <code>string msgType = 2;</code>
     * @return The msgType.
     */
    String getMsgType();
    /**
     * <pre>
     *&#47;&lt; 消息类型
     * </pre>
     *
     * <code>string msgType = 2;</code>
     * @return The bytes for msgType.
     */
    com.google.protobuf.ByteString
        getMsgTypeBytes();

    /**
     * <pre>
     *&#47;&lt; 消息发送时间，unix 时间戳, 单位：ms
     * </pre>
     *
     * <code>uint64 msgTime = 3;</code>
     * @return The msgTime.
     */
    long getMsgTime();

    /**
     * <pre>
     *&#47;&lt; 车辆位置，包含位置、速度、航向等
     * </pre>
     *
     * <code>.com.dpi.map.cabin.domain.proto.VehiclePVT vehiclePos = 4;</code>
     * @return Whether the vehiclePos field is set.
     */
    boolean hasVehiclePos();
    /**
     * <pre>
     *&#47;&lt; 车辆位置，包含位置、速度、航向等
     * </pre>
     *
     * <code>.com.dpi.map.cabin.domain.proto.VehiclePVT vehiclePos = 4;</code>
     * @return The vehiclePos.
     */
    com.dpi.map.cabin.domain.proto.DpiMeOutput.VehiclePVT getVehiclePos();
    /**
     * <pre>
     *&#47;&lt; 车辆位置，包含位置、速度、航向等
     * </pre>
     *
     * <code>.com.dpi.map.cabin.domain.proto.VehiclePVT vehiclePos = 4;</code>
     */
    com.dpi.map.cabin.domain.proto.DpiMeOutput.VehiclePVTOrBuilder getVehiclePosOrBuilder();
  }
  /**
   * <pre>
   **
   * &#64;brief 车辆位置消息结构体
   * </pre>
   *
   * Protobuf type {@code com.dpi.map.cabin.domain.proto.PositionMsg}
   */
  public static final class PositionMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.dpi.map.cabin.domain.proto.PositionMsg)
      PositionMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PositionMsg.newBuilder() to construct.
    private PositionMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PositionMsg() {
      msgType_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new PositionMsg();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PositionMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              msgId_ = input.readUInt32();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              msgType_ = s;
              break;
            }
            case 24: {

              msgTime_ = input.readUInt64();
              break;
            }
            case 34: {
              com.dpi.map.cabin.domain.proto.DpiMeOutput.VehiclePVT.Builder subBuilder = null;
              if (vehiclePos_ != null) {
                subBuilder = vehiclePos_.toBuilder();
              }
              vehiclePos_ = input.readMessage(com.dpi.map.cabin.domain.proto.DpiMeOutput.VehiclePVT.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(vehiclePos_);
                vehiclePos_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dpi.map.cabin.domain.proto.DpiMeOutput.internal_static_dpi_comm_mapengine_PositionMsg_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dpi.map.cabin.domain.proto.DpiMeOutput.internal_static_dpi_comm_mapengine_PositionMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dpi.map.cabin.domain.proto.DpiMeOutput.PositionMsg.class, com.dpi.map.cabin.domain.proto.DpiMeOutput.PositionMsg.Builder.class);
    }

    public static final int MSGID_FIELD_NUMBER = 1;
    private int msgId_;
    /**
     * <pre>
     *&#47;&lt; 消息id
     * </pre>
     *
     * <code>uint32 msgId = 1;</code>
     * @return The msgId.
     */
    @Override
    public int getMsgId() {
      return msgId_;
    }

    public static final int MSGTYPE_FIELD_NUMBER = 2;
    private volatile Object msgType_;
    /**
     * <pre>
     *&#47;&lt; 消息类型
     * </pre>
     *
     * <code>string msgType = 2;</code>
     * @return The msgType.
     */
    @Override
    public String getMsgType() {
      Object ref = msgType_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        msgType_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *&#47;&lt; 消息类型
     * </pre>
     *
     * <code>string msgType = 2;</code>
     * @return The bytes for msgType.
     */
    @Override
    public com.google.protobuf.ByteString
        getMsgTypeBytes() {
      Object ref = msgType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        msgType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MSGTIME_FIELD_NUMBER = 3;
    private long msgTime_;
    /**
     * <pre>
     *&#47;&lt; 消息发送时间，unix 时间戳, 单位：ms
     * </pre>
     *
     * <code>uint64 msgTime = 3;</code>
     * @return The msgTime.
     */
    @Override
    public long getMsgTime() {
      return msgTime_;
    }

    public static final int VEHICLEPOS_FIELD_NUMBER = 4;
    private com.dpi.map.cabin.domain.proto.DpiMeOutput.VehiclePVT vehiclePos_;
    /**
     * <pre>
     *&#47;&lt; 车辆位置，包含位置、速度、航向等
     * </pre>
     *
     * <code>.com.dpi.map.cabin.domain.proto.VehiclePVT vehiclePos = 4;</code>
     * @return Whether the vehiclePos field is set.
     */
    @Override
    public boolean hasVehiclePos() {
      return vehiclePos_ != null;
    }
    /**
     * <pre>
     *&#47;&lt; 车辆位置，包含位置、速度、航向等
     * </pre>
     *
     * <code>.com.dpi.map.cabin.domain.proto.VehiclePVT vehiclePos = 4;</code>
     * @return The vehiclePos.
     */
    @Override
    public com.dpi.map.cabin.domain.proto.DpiMeOutput.VehiclePVT getVehiclePos() {
      return vehiclePos_ == null ? com.dpi.map.cabin.domain.proto.DpiMeOutput.VehiclePVT.getDefaultInstance() : vehiclePos_;
    }
    /**
     * <pre>
     *&#47;&lt; 车辆位置，包含位置、速度、航向等
     * </pre>
     *
     * <code>.com.dpi.map.cabin.domain.proto.VehiclePVT vehiclePos = 4;</code>
     */
    @Override
    public com.dpi.map.cabin.domain.proto.DpiMeOutput.VehiclePVTOrBuilder getVehiclePosOrBuilder() {
      return getVehiclePos();
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (msgId_ != 0) {
        output.writeUInt32(1, msgId_);
      }
      if (!getMsgTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, msgType_);
      }
      if (msgTime_ != 0L) {
        output.writeUInt64(3, msgTime_);
      }
      if (vehiclePos_ != null) {
        output.writeMessage(4, getVehiclePos());
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (msgId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, msgId_);
      }
      if (!getMsgTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, msgType_);
      }
      if (msgTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, msgTime_);
      }
      if (vehiclePos_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getVehiclePos());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.dpi.map.cabin.domain.proto.DpiMeOutput.PositionMsg)) {
        return super.equals(obj);
      }
      com.dpi.map.cabin.domain.proto.DpiMeOutput.PositionMsg other = (com.dpi.map.cabin.domain.proto.DpiMeOutput.PositionMsg) obj;

      if (getMsgId()
          != other.getMsgId()) return false;
      if (!getMsgType()
          .equals(other.getMsgType())) return false;
      if (getMsgTime()
          != other.getMsgTime()) return false;
      if (hasVehiclePos() != other.hasVehiclePos()) return false;
      if (hasVehiclePos()) {
        if (!getVehiclePos()
            .equals(other.getVehiclePos())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MSGID_FIELD_NUMBER;
      hash = (53 * hash) + getMsgId();
      hash = (37 * hash) + MSGTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getMsgType().hashCode();
      hash = (37 * hash) + MSGTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMsgTime());
      if (hasVehiclePos()) {
        hash = (37 * hash) + VEHICLEPOS_FIELD_NUMBER;
        hash = (53 * hash) + getVehiclePos().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.dpi.map.cabin.domain.proto.DpiMeOutput.PositionMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dpi.map.cabin.domain.proto.DpiMeOutput.PositionMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dpi.map.cabin.domain.proto.DpiMeOutput.PositionMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dpi.map.cabin.domain.proto.DpiMeOutput.PositionMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dpi.map.cabin.domain.proto.DpiMeOutput.PositionMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dpi.map.cabin.domain.proto.DpiMeOutput.PositionMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dpi.map.cabin.domain.proto.DpiMeOutput.PositionMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dpi.map.cabin.domain.proto.DpiMeOutput.PositionMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dpi.map.cabin.domain.proto.DpiMeOutput.PositionMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.dpi.map.cabin.domain.proto.DpiMeOutput.PositionMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dpi.map.cabin.domain.proto.DpiMeOutput.PositionMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dpi.map.cabin.domain.proto.DpiMeOutput.PositionMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.dpi.map.cabin.domain.proto.DpiMeOutput.PositionMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     **
     * &#64;brief 车辆位置消息结构体
     * </pre>
     *
     * Protobuf type {@code com.dpi.map.cabin.domain.proto.PositionMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.dpi.map.cabin.domain.proto.PositionMsg)
        com.dpi.map.cabin.domain.proto.DpiMeOutput.PositionMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dpi.map.cabin.domain.proto.DpiMeOutput.internal_static_dpi_comm_mapengine_PositionMsg_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dpi.map.cabin.domain.proto.DpiMeOutput.internal_static_dpi_comm_mapengine_PositionMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.dpi.map.cabin.domain.proto.DpiMeOutput.PositionMsg.class, com.dpi.map.cabin.domain.proto.DpiMeOutput.PositionMsg.Builder.class);
      }

      // Construct using com.dpi.map.cabin.domain.proto.DpiMeOutput.PositionMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        msgId_ = 0;

        msgType_ = "";

        msgTime_ = 0L;

        if (vehiclePosBuilder_ == null) {
          vehiclePos_ = null;
        } else {
          vehiclePos_ = null;
          vehiclePosBuilder_ = null;
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dpi.map.cabin.domain.proto.DpiMeOutput.internal_static_dpi_comm_mapengine_PositionMsg_descriptor;
      }

      @Override
      public com.dpi.map.cabin.domain.proto.DpiMeOutput.PositionMsg getDefaultInstanceForType() {
        return com.dpi.map.cabin.domain.proto.DpiMeOutput.PositionMsg.getDefaultInstance();
      }

      @Override
      public com.dpi.map.cabin.domain.proto.DpiMeOutput.PositionMsg build() {
        com.dpi.map.cabin.domain.proto.DpiMeOutput.PositionMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public com.dpi.map.cabin.domain.proto.DpiMeOutput.PositionMsg buildPartial() {
        com.dpi.map.cabin.domain.proto.DpiMeOutput.PositionMsg result = new com.dpi.map.cabin.domain.proto.DpiMeOutput.PositionMsg(this);
        result.msgId_ = msgId_;
        result.msgType_ = msgType_;
        result.msgTime_ = msgTime_;
        if (vehiclePosBuilder_ == null) {
          result.vehiclePos_ = vehiclePos_;
        } else {
          result.vehiclePos_ = vehiclePosBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dpi.map.cabin.domain.proto.DpiMeOutput.PositionMsg) {
          return mergeFrom((com.dpi.map.cabin.domain.proto.DpiMeOutput.PositionMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.dpi.map.cabin.domain.proto.DpiMeOutput.PositionMsg other) {
        if (other == com.dpi.map.cabin.domain.proto.DpiMeOutput.PositionMsg.getDefaultInstance()) return this;
        if (other.getMsgId() != 0) {
          setMsgId(other.getMsgId());
        }
        if (!other.getMsgType().isEmpty()) {
          msgType_ = other.msgType_;
          onChanged();
        }
        if (other.getMsgTime() != 0L) {
          setMsgTime(other.getMsgTime());
        }
        if (other.hasVehiclePos()) {
          mergeVehiclePos(other.getVehiclePos());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.dpi.map.cabin.domain.proto.DpiMeOutput.PositionMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.dpi.map.cabin.domain.proto.DpiMeOutput.PositionMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int msgId_ ;
      /**
       * <pre>
       *&#47;&lt; 消息id
       * </pre>
       *
       * <code>uint32 msgId = 1;</code>
       * @return The msgId.
       */
      @Override
      public int getMsgId() {
        return msgId_;
      }
      /**
       * <pre>
       *&#47;&lt; 消息id
       * </pre>
       *
       * <code>uint32 msgId = 1;</code>
       * @param value The msgId to set.
       * @return This builder for chaining.
       */
      public Builder setMsgId(int value) {
        
        msgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *&#47;&lt; 消息id
       * </pre>
       *
       * <code>uint32 msgId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgId() {
        
        msgId_ = 0;
        onChanged();
        return this;
      }

      private Object msgType_ = "";
      /**
       * <pre>
       *&#47;&lt; 消息类型
       * </pre>
       *
       * <code>string msgType = 2;</code>
       * @return The msgType.
       */
      public String getMsgType() {
        Object ref = msgType_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          msgType_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *&#47;&lt; 消息类型
       * </pre>
       *
       * <code>string msgType = 2;</code>
       * @return The bytes for msgType.
       */
      public com.google.protobuf.ByteString
          getMsgTypeBytes() {
        Object ref = msgType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          msgType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *&#47;&lt; 消息类型
       * </pre>
       *
       * <code>string msgType = 2;</code>
       * @param value The msgType to set.
       * @return This builder for chaining.
       */
      public Builder setMsgType(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msgType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *&#47;&lt; 消息类型
       * </pre>
       *
       * <code>string msgType = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgType() {
        
        msgType_ = getDefaultInstance().getMsgType();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *&#47;&lt; 消息类型
       * </pre>
       *
       * <code>string msgType = 2;</code>
       * @param value The bytes for msgType to set.
       * @return This builder for chaining.
       */
      public Builder setMsgTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msgType_ = value;
        onChanged();
        return this;
      }

      private long msgTime_ ;
      /**
       * <pre>
       *&#47;&lt; 消息发送时间，unix 时间戳, 单位：ms
       * </pre>
       *
       * <code>uint64 msgTime = 3;</code>
       * @return The msgTime.
       */
      @Override
      public long getMsgTime() {
        return msgTime_;
      }
      /**
       * <pre>
       *&#47;&lt; 消息发送时间，unix 时间戳, 单位：ms
       * </pre>
       *
       * <code>uint64 msgTime = 3;</code>
       * @param value The msgTime to set.
       * @return This builder for chaining.
       */
      public Builder setMsgTime(long value) {
        
        msgTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *&#47;&lt; 消息发送时间，unix 时间戳, 单位：ms
       * </pre>
       *
       * <code>uint64 msgTime = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgTime() {
        
        msgTime_ = 0L;
        onChanged();
        return this;
      }

      private com.dpi.map.cabin.domain.proto.DpiMeOutput.VehiclePVT vehiclePos_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.dpi.map.cabin.domain.proto.DpiMeOutput.VehiclePVT, com.dpi.map.cabin.domain.proto.DpiMeOutput.VehiclePVT.Builder, com.dpi.map.cabin.domain.proto.DpiMeOutput.VehiclePVTOrBuilder> vehiclePosBuilder_;
      /**
       * <pre>
       *&#47;&lt; 车辆位置，包含位置、速度、航向等
       * </pre>
       *
       * <code>.com.dpi.map.cabin.domain.proto.VehiclePVT vehiclePos = 4;</code>
       * @return Whether the vehiclePos field is set.
       */
      public boolean hasVehiclePos() {
        return vehiclePosBuilder_ != null || vehiclePos_ != null;
      }
      /**
       * <pre>
       *&#47;&lt; 车辆位置，包含位置、速度、航向等
       * </pre>
       *
       * <code>.com.dpi.map.cabin.domain.proto.VehiclePVT vehiclePos = 4;</code>
       * @return The vehiclePos.
       */
      public com.dpi.map.cabin.domain.proto.DpiMeOutput.VehiclePVT getVehiclePos() {
        if (vehiclePosBuilder_ == null) {
          return vehiclePos_ == null ? com.dpi.map.cabin.domain.proto.DpiMeOutput.VehiclePVT.getDefaultInstance() : vehiclePos_;
        } else {
          return vehiclePosBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *&#47;&lt; 车辆位置，包含位置、速度、航向等
       * </pre>
       *
       * <code>.com.dpi.map.cabin.domain.proto.VehiclePVT vehiclePos = 4;</code>
       */
      public Builder setVehiclePos(com.dpi.map.cabin.domain.proto.DpiMeOutput.VehiclePVT value) {
        if (vehiclePosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          vehiclePos_ = value;
          onChanged();
        } else {
          vehiclePosBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       *&#47;&lt; 车辆位置，包含位置、速度、航向等
       * </pre>
       *
       * <code>.com.dpi.map.cabin.domain.proto.VehiclePVT vehiclePos = 4;</code>
       */
      public Builder setVehiclePos(
          com.dpi.map.cabin.domain.proto.DpiMeOutput.VehiclePVT.Builder builderForValue) {
        if (vehiclePosBuilder_ == null) {
          vehiclePos_ = builderForValue.build();
          onChanged();
        } else {
          vehiclePosBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       *&#47;&lt; 车辆位置，包含位置、速度、航向等
       * </pre>
       *
       * <code>.com.dpi.map.cabin.domain.proto.VehiclePVT vehiclePos = 4;</code>
       */
      public Builder mergeVehiclePos(com.dpi.map.cabin.domain.proto.DpiMeOutput.VehiclePVT value) {
        if (vehiclePosBuilder_ == null) {
          if (vehiclePos_ != null) {
            vehiclePos_ =
              com.dpi.map.cabin.domain.proto.DpiMeOutput.VehiclePVT.newBuilder(vehiclePos_).mergeFrom(value).buildPartial();
          } else {
            vehiclePos_ = value;
          }
          onChanged();
        } else {
          vehiclePosBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       *&#47;&lt; 车辆位置，包含位置、速度、航向等
       * </pre>
       *
       * <code>.com.dpi.map.cabin.domain.proto.VehiclePVT vehiclePos = 4;</code>
       */
      public Builder clearVehiclePos() {
        if (vehiclePosBuilder_ == null) {
          vehiclePos_ = null;
          onChanged();
        } else {
          vehiclePos_ = null;
          vehiclePosBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       *&#47;&lt; 车辆位置，包含位置、速度、航向等
       * </pre>
       *
       * <code>.com.dpi.map.cabin.domain.proto.VehiclePVT vehiclePos = 4;</code>
       */
      public com.dpi.map.cabin.domain.proto.DpiMeOutput.VehiclePVT.Builder getVehiclePosBuilder() {
        
        onChanged();
        return getVehiclePosFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *&#47;&lt; 车辆位置，包含位置、速度、航向等
       * </pre>
       *
       * <code>.com.dpi.map.cabin.domain.proto.VehiclePVT vehiclePos = 4;</code>
       */
      public com.dpi.map.cabin.domain.proto.DpiMeOutput.VehiclePVTOrBuilder getVehiclePosOrBuilder() {
        if (vehiclePosBuilder_ != null) {
          return vehiclePosBuilder_.getMessageOrBuilder();
        } else {
          return vehiclePos_ == null ?
              com.dpi.map.cabin.domain.proto.DpiMeOutput.VehiclePVT.getDefaultInstance() : vehiclePos_;
        }
      }
      /**
       * <pre>
       *&#47;&lt; 车辆位置，包含位置、速度、航向等
       * </pre>
       *
       * <code>.com.dpi.map.cabin.domain.proto.VehiclePVT vehiclePos = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.dpi.map.cabin.domain.proto.DpiMeOutput.VehiclePVT, com.dpi.map.cabin.domain.proto.DpiMeOutput.VehiclePVT.Builder, com.dpi.map.cabin.domain.proto.DpiMeOutput.VehiclePVTOrBuilder> 
          getVehiclePosFieldBuilder() {
        if (vehiclePosBuilder_ == null) {
          vehiclePosBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.dpi.map.cabin.domain.proto.DpiMeOutput.VehiclePVT, com.dpi.map.cabin.domain.proto.DpiMeOutput.VehiclePVT.Builder, com.dpi.map.cabin.domain.proto.DpiMeOutput.VehiclePVTOrBuilder>(
                  getVehiclePos(),
                  getParentForChildren(),
                  isClean());
          vehiclePos_ = null;
        }
        return vehiclePosBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.dpi.map.cabin.domain.proto.PositionMsg)
    }

    // @@protoc_insertion_point(class_scope:com.dpi.map.cabin.domain.proto.PositionMsg)
    private static final com.dpi.map.cabin.domain.proto.DpiMeOutput.PositionMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.dpi.map.cabin.domain.proto.DpiMeOutput.PositionMsg();
    }

    public static com.dpi.map.cabin.domain.proto.DpiMeOutput.PositionMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PositionMsg>
        PARSER = new com.google.protobuf.AbstractParser<PositionMsg>() {
      @Override
      public PositionMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PositionMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PositionMsg> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<PositionMsg> getParserForType() {
      return PARSER;
    }

    @Override
    public com.dpi.map.cabin.domain.proto.DpiMeOutput.PositionMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface VehiclePVTOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.dpi.map.cabin.domain.proto.VehiclePVT)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *&#47;&lt; 位置对应的时间戳，unix时间，单位：ms
     * </pre>
     *
     * <code>uint64 time = 1;</code>
     * @return The time.
     */
    long getTime();

    /**
     * <pre>
     *&#47;&lt; 车辆位姿，包含三轴位置和姿态
     * </pre>
     *
     * <code>.com.dpi.map.cabin.domain.proto.CPoint6D point6D = 2;</code>
     * @return Whether the point6D field is set.
     */
    boolean hasPoint6D();
    /**
     * <pre>
     *&#47;&lt; 车辆位姿，包含三轴位置和姿态
     * </pre>
     *
     * <code>.com.dpi.map.cabin.domain.proto.CPoint6D point6D = 2;</code>
     * @return The point6D.
     */
    com.dpi.map.cabin.domain.proto.DpiMeOutput.CPoint6D getPoint6D();
    /**
     * <pre>
     *&#47;&lt; 车辆位姿，包含三轴位置和姿态
     * </pre>
     *
     * <code>.com.dpi.map.cabin.domain.proto.CPoint6D point6D = 2;</code>
     */
    com.dpi.map.cabin.domain.proto.DpiMeOutput.CPoint6DOrBuilder getPoint6DOrBuilder();

    /**
     * <pre>
     *&#47;&lt; 车速，m/s
     * </pre>
     *
     * <code>double speed = 3;</code>
     * @return The speed.
     */
    double getSpeed();

    /**
     * <pre>
     *&#47;&lt; 位置置信度，最高为100，默认为100
     * </pre>
     *
     * <code>uint32 confidence = 4;</code>
     * @return The confidence.
     */
    int getConfidence();
  }
  /**
   * <pre>
   **
   * &#64;brief 车辆位置消息结构体
   * </pre>
   *
   * Protobuf type {@code com.dpi.map.cabin.domain.proto.VehiclePVT}
   */
  public static final class VehiclePVT extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.dpi.map.cabin.domain.proto.VehiclePVT)
      VehiclePVTOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use VehiclePVT.newBuilder() to construct.
    private VehiclePVT(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private VehiclePVT() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new VehiclePVT();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private VehiclePVT(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              time_ = input.readUInt64();
              break;
            }
            case 18: {
              com.dpi.map.cabin.domain.proto.DpiMeOutput.CPoint6D.Builder subBuilder = null;
              if (point6D_ != null) {
                subBuilder = point6D_.toBuilder();
              }
              point6D_ = input.readMessage(com.dpi.map.cabin.domain.proto.DpiMeOutput.CPoint6D.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(point6D_);
                point6D_ = subBuilder.buildPartial();
              }

              break;
            }
            case 25: {

              speed_ = input.readDouble();
              break;
            }
            case 32: {

              confidence_ = input.readUInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dpi.map.cabin.domain.proto.DpiMeOutput.internal_static_dpi_comm_mapengine_VehiclePVT_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dpi.map.cabin.domain.proto.DpiMeOutput.internal_static_dpi_comm_mapengine_VehiclePVT_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dpi.map.cabin.domain.proto.DpiMeOutput.VehiclePVT.class, com.dpi.map.cabin.domain.proto.DpiMeOutput.VehiclePVT.Builder.class);
    }

    public static final int TIME_FIELD_NUMBER = 1;
    private long time_;
    /**
     * <pre>
     *&#47;&lt; 位置对应的时间戳，unix时间，单位：ms
     * </pre>
     *
     * <code>uint64 time = 1;</code>
     * @return The time.
     */
    @Override
    public long getTime() {
      return time_;
    }

    public static final int POINT6D_FIELD_NUMBER = 2;
    private com.dpi.map.cabin.domain.proto.DpiMeOutput.CPoint6D point6D_;
    /**
     * <pre>
     *&#47;&lt; 车辆位姿，包含三轴位置和姿态
     * </pre>
     *
     * <code>.com.dpi.map.cabin.domain.proto.CPoint6D point6D = 2;</code>
     * @return Whether the point6D field is set.
     */
    @Override
    public boolean hasPoint6D() {
      return point6D_ != null;
    }
    /**
     * <pre>
     *&#47;&lt; 车辆位姿，包含三轴位置和姿态
     * </pre>
     *
     * <code>.com.dpi.map.cabin.domain.proto.CPoint6D point6D = 2;</code>
     * @return The point6D.
     */
    @Override
    public com.dpi.map.cabin.domain.proto.DpiMeOutput.CPoint6D getPoint6D() {
      return point6D_ == null ? com.dpi.map.cabin.domain.proto.DpiMeOutput.CPoint6D.getDefaultInstance() : point6D_;
    }
    /**
     * <pre>
     *&#47;&lt; 车辆位姿，包含三轴位置和姿态
     * </pre>
     *
     * <code>.com.dpi.map.cabin.domain.proto.CPoint6D point6D = 2;</code>
     */
    @Override
    public com.dpi.map.cabin.domain.proto.DpiMeOutput.CPoint6DOrBuilder getPoint6DOrBuilder() {
      return getPoint6D();
    }

    public static final int SPEED_FIELD_NUMBER = 3;
    private double speed_;
    /**
     * <pre>
     *&#47;&lt; 车速，m/s
     * </pre>
     *
     * <code>double speed = 3;</code>
     * @return The speed.
     */
    @Override
    public double getSpeed() {
      return speed_;
    }

    public static final int CONFIDENCE_FIELD_NUMBER = 4;
    private int confidence_;
    /**
     * <pre>
     *&#47;&lt; 位置置信度，最高为100，默认为100
     * </pre>
     *
     * <code>uint32 confidence = 4;</code>
     * @return The confidence.
     */
    @Override
    public int getConfidence() {
      return confidence_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (time_ != 0L) {
        output.writeUInt64(1, time_);
      }
      if (point6D_ != null) {
        output.writeMessage(2, getPoint6D());
      }
      if (speed_ != 0D) {
        output.writeDouble(3, speed_);
      }
      if (confidence_ != 0) {
        output.writeUInt32(4, confidence_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (time_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, time_);
      }
      if (point6D_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getPoint6D());
      }
      if (speed_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, speed_);
      }
      if (confidence_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, confidence_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.dpi.map.cabin.domain.proto.DpiMeOutput.VehiclePVT)) {
        return super.equals(obj);
      }
      com.dpi.map.cabin.domain.proto.DpiMeOutput.VehiclePVT other = (com.dpi.map.cabin.domain.proto.DpiMeOutput.VehiclePVT) obj;

      if (getTime()
          != other.getTime()) return false;
      if (hasPoint6D() != other.hasPoint6D()) return false;
      if (hasPoint6D()) {
        if (!getPoint6D()
            .equals(other.getPoint6D())) return false;
      }
      if (Double.doubleToLongBits(getSpeed())
          != Double.doubleToLongBits(
              other.getSpeed())) return false;
      if (getConfidence()
          != other.getConfidence()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTime());
      if (hasPoint6D()) {
        hash = (37 * hash) + POINT6D_FIELD_NUMBER;
        hash = (53 * hash) + getPoint6D().hashCode();
      }
      hash = (37 * hash) + SPEED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getSpeed()));
      hash = (37 * hash) + CONFIDENCE_FIELD_NUMBER;
      hash = (53 * hash) + getConfidence();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.dpi.map.cabin.domain.proto.DpiMeOutput.VehiclePVT parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dpi.map.cabin.domain.proto.DpiMeOutput.VehiclePVT parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dpi.map.cabin.domain.proto.DpiMeOutput.VehiclePVT parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dpi.map.cabin.domain.proto.DpiMeOutput.VehiclePVT parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dpi.map.cabin.domain.proto.DpiMeOutput.VehiclePVT parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dpi.map.cabin.domain.proto.DpiMeOutput.VehiclePVT parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dpi.map.cabin.domain.proto.DpiMeOutput.VehiclePVT parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dpi.map.cabin.domain.proto.DpiMeOutput.VehiclePVT parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dpi.map.cabin.domain.proto.DpiMeOutput.VehiclePVT parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.dpi.map.cabin.domain.proto.DpiMeOutput.VehiclePVT parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dpi.map.cabin.domain.proto.DpiMeOutput.VehiclePVT parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dpi.map.cabin.domain.proto.DpiMeOutput.VehiclePVT parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.dpi.map.cabin.domain.proto.DpiMeOutput.VehiclePVT prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     **
     * &#64;brief 车辆位置消息结构体
     * </pre>
     *
     * Protobuf type {@code com.dpi.map.cabin.domain.proto.VehiclePVT}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.dpi.map.cabin.domain.proto.VehiclePVT)
        com.dpi.map.cabin.domain.proto.DpiMeOutput.VehiclePVTOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dpi.map.cabin.domain.proto.DpiMeOutput.internal_static_dpi_comm_mapengine_VehiclePVT_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dpi.map.cabin.domain.proto.DpiMeOutput.internal_static_dpi_comm_mapengine_VehiclePVT_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.dpi.map.cabin.domain.proto.DpiMeOutput.VehiclePVT.class, com.dpi.map.cabin.domain.proto.DpiMeOutput.VehiclePVT.Builder.class);
      }

      // Construct using com.dpi.map.cabin.domain.proto.DpiMeOutput.VehiclePVT.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        time_ = 0L;

        if (point6DBuilder_ == null) {
          point6D_ = null;
        } else {
          point6D_ = null;
          point6DBuilder_ = null;
        }
        speed_ = 0D;

        confidence_ = 0;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dpi.map.cabin.domain.proto.DpiMeOutput.internal_static_dpi_comm_mapengine_VehiclePVT_descriptor;
      }

      @Override
      public com.dpi.map.cabin.domain.proto.DpiMeOutput.VehiclePVT getDefaultInstanceForType() {
        return com.dpi.map.cabin.domain.proto.DpiMeOutput.VehiclePVT.getDefaultInstance();
      }

      @Override
      public com.dpi.map.cabin.domain.proto.DpiMeOutput.VehiclePVT build() {
        com.dpi.map.cabin.domain.proto.DpiMeOutput.VehiclePVT result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public com.dpi.map.cabin.domain.proto.DpiMeOutput.VehiclePVT buildPartial() {
        com.dpi.map.cabin.domain.proto.DpiMeOutput.VehiclePVT result = new com.dpi.map.cabin.domain.proto.DpiMeOutput.VehiclePVT(this);
        result.time_ = time_;
        if (point6DBuilder_ == null) {
          result.point6D_ = point6D_;
        } else {
          result.point6D_ = point6DBuilder_.build();
        }
        result.speed_ = speed_;
        result.confidence_ = confidence_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dpi.map.cabin.domain.proto.DpiMeOutput.VehiclePVT) {
          return mergeFrom((com.dpi.map.cabin.domain.proto.DpiMeOutput.VehiclePVT)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.dpi.map.cabin.domain.proto.DpiMeOutput.VehiclePVT other) {
        if (other == com.dpi.map.cabin.domain.proto.DpiMeOutput.VehiclePVT.getDefaultInstance()) return this;
        if (other.getTime() != 0L) {
          setTime(other.getTime());
        }
        if (other.hasPoint6D()) {
          mergePoint6D(other.getPoint6D());
        }
        if (other.getSpeed() != 0D) {
          setSpeed(other.getSpeed());
        }
        if (other.getConfidence() != 0) {
          setConfidence(other.getConfidence());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.dpi.map.cabin.domain.proto.DpiMeOutput.VehiclePVT parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.dpi.map.cabin.domain.proto.DpiMeOutput.VehiclePVT) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long time_ ;
      /**
       * <pre>
       *&#47;&lt; 位置对应的时间戳，unix时间，单位：ms
       * </pre>
       *
       * <code>uint64 time = 1;</code>
       * @return The time.
       */
      @Override
      public long getTime() {
        return time_;
      }
      /**
       * <pre>
       *&#47;&lt; 位置对应的时间戳，unix时间，单位：ms
       * </pre>
       *
       * <code>uint64 time = 1;</code>
       * @param value The time to set.
       * @return This builder for chaining.
       */
      public Builder setTime(long value) {
        
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *&#47;&lt; 位置对应的时间戳，unix时间，单位：ms
       * </pre>
       *
       * <code>uint64 time = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTime() {
        
        time_ = 0L;
        onChanged();
        return this;
      }

      private com.dpi.map.cabin.domain.proto.DpiMeOutput.CPoint6D point6D_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.dpi.map.cabin.domain.proto.DpiMeOutput.CPoint6D, com.dpi.map.cabin.domain.proto.DpiMeOutput.CPoint6D.Builder, com.dpi.map.cabin.domain.proto.DpiMeOutput.CPoint6DOrBuilder> point6DBuilder_;
      /**
       * <pre>
       *&#47;&lt; 车辆位姿，包含三轴位置和姿态
       * </pre>
       *
       * <code>.com.dpi.map.cabin.domain.proto.CPoint6D point6D = 2;</code>
       * @return Whether the point6D field is set.
       */
      public boolean hasPoint6D() {
        return point6DBuilder_ != null || point6D_ != null;
      }
      /**
       * <pre>
       *&#47;&lt; 车辆位姿，包含三轴位置和姿态
       * </pre>
       *
       * <code>.com.dpi.map.cabin.domain.proto.CPoint6D point6D = 2;</code>
       * @return The point6D.
       */
      public com.dpi.map.cabin.domain.proto.DpiMeOutput.CPoint6D getPoint6D() {
        if (point6DBuilder_ == null) {
          return point6D_ == null ? com.dpi.map.cabin.domain.proto.DpiMeOutput.CPoint6D.getDefaultInstance() : point6D_;
        } else {
          return point6DBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *&#47;&lt; 车辆位姿，包含三轴位置和姿态
       * </pre>
       *
       * <code>.com.dpi.map.cabin.domain.proto.CPoint6D point6D = 2;</code>
       */
      public Builder setPoint6D(com.dpi.map.cabin.domain.proto.DpiMeOutput.CPoint6D value) {
        if (point6DBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          point6D_ = value;
          onChanged();
        } else {
          point6DBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       *&#47;&lt; 车辆位姿，包含三轴位置和姿态
       * </pre>
       *
       * <code>.com.dpi.map.cabin.domain.proto.CPoint6D point6D = 2;</code>
       */
      public Builder setPoint6D(
          com.dpi.map.cabin.domain.proto.DpiMeOutput.CPoint6D.Builder builderForValue) {
        if (point6DBuilder_ == null) {
          point6D_ = builderForValue.build();
          onChanged();
        } else {
          point6DBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       *&#47;&lt; 车辆位姿，包含三轴位置和姿态
       * </pre>
       *
       * <code>.com.dpi.map.cabin.domain.proto.CPoint6D point6D = 2;</code>
       */
      public Builder mergePoint6D(com.dpi.map.cabin.domain.proto.DpiMeOutput.CPoint6D value) {
        if (point6DBuilder_ == null) {
          if (point6D_ != null) {
            point6D_ =
              com.dpi.map.cabin.domain.proto.DpiMeOutput.CPoint6D.newBuilder(point6D_).mergeFrom(value).buildPartial();
          } else {
            point6D_ = value;
          }
          onChanged();
        } else {
          point6DBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       *&#47;&lt; 车辆位姿，包含三轴位置和姿态
       * </pre>
       *
       * <code>.com.dpi.map.cabin.domain.proto.CPoint6D point6D = 2;</code>
       */
      public Builder clearPoint6D() {
        if (point6DBuilder_ == null) {
          point6D_ = null;
          onChanged();
        } else {
          point6D_ = null;
          point6DBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       *&#47;&lt; 车辆位姿，包含三轴位置和姿态
       * </pre>
       *
       * <code>.com.dpi.map.cabin.domain.proto.CPoint6D point6D = 2;</code>
       */
      public com.dpi.map.cabin.domain.proto.DpiMeOutput.CPoint6D.Builder getPoint6DBuilder() {
        
        onChanged();
        return getPoint6DFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *&#47;&lt; 车辆位姿，包含三轴位置和姿态
       * </pre>
       *
       * <code>.com.dpi.map.cabin.domain.proto.CPoint6D point6D = 2;</code>
       */
      public com.dpi.map.cabin.domain.proto.DpiMeOutput.CPoint6DOrBuilder getPoint6DOrBuilder() {
        if (point6DBuilder_ != null) {
          return point6DBuilder_.getMessageOrBuilder();
        } else {
          return point6D_ == null ?
              com.dpi.map.cabin.domain.proto.DpiMeOutput.CPoint6D.getDefaultInstance() : point6D_;
        }
      }
      /**
       * <pre>
       *&#47;&lt; 车辆位姿，包含三轴位置和姿态
       * </pre>
       *
       * <code>.com.dpi.map.cabin.domain.proto.CPoint6D point6D = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.dpi.map.cabin.domain.proto.DpiMeOutput.CPoint6D, com.dpi.map.cabin.domain.proto.DpiMeOutput.CPoint6D.Builder, com.dpi.map.cabin.domain.proto.DpiMeOutput.CPoint6DOrBuilder> 
          getPoint6DFieldBuilder() {
        if (point6DBuilder_ == null) {
          point6DBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.dpi.map.cabin.domain.proto.DpiMeOutput.CPoint6D, com.dpi.map.cabin.domain.proto.DpiMeOutput.CPoint6D.Builder, com.dpi.map.cabin.domain.proto.DpiMeOutput.CPoint6DOrBuilder>(
                  getPoint6D(),
                  getParentForChildren(),
                  isClean());
          point6D_ = null;
        }
        return point6DBuilder_;
      }

      private double speed_ ;
      /**
       * <pre>
       *&#47;&lt; 车速，m/s
       * </pre>
       *
       * <code>double speed = 3;</code>
       * @return The speed.
       */
      @Override
      public double getSpeed() {
        return speed_;
      }
      /**
       * <pre>
       *&#47;&lt; 车速，m/s
       * </pre>
       *
       * <code>double speed = 3;</code>
       * @param value The speed to set.
       * @return This builder for chaining.
       */
      public Builder setSpeed(double value) {
        
        speed_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *&#47;&lt; 车速，m/s
       * </pre>
       *
       * <code>double speed = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSpeed() {
        
        speed_ = 0D;
        onChanged();
        return this;
      }

      private int confidence_ ;
      /**
       * <pre>
       *&#47;&lt; 位置置信度，最高为100，默认为100
       * </pre>
       *
       * <code>uint32 confidence = 4;</code>
       * @return The confidence.
       */
      @Override
      public int getConfidence() {
        return confidence_;
      }
      /**
       * <pre>
       *&#47;&lt; 位置置信度，最高为100，默认为100
       * </pre>
       *
       * <code>uint32 confidence = 4;</code>
       * @param value The confidence to set.
       * @return This builder for chaining.
       */
      public Builder setConfidence(int value) {
        
        confidence_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *&#47;&lt; 位置置信度，最高为100，默认为100
       * </pre>
       *
       * <code>uint32 confidence = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearConfidence() {
        
        confidence_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.dpi.map.cabin.domain.proto.VehiclePVT)
    }

    // @@protoc_insertion_point(class_scope:com.dpi.map.cabin.domain.proto.VehiclePVT)
    private static final com.dpi.map.cabin.domain.proto.DpiMeOutput.VehiclePVT DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.dpi.map.cabin.domain.proto.DpiMeOutput.VehiclePVT();
    }

    public static com.dpi.map.cabin.domain.proto.DpiMeOutput.VehiclePVT getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<VehiclePVT>
        PARSER = new com.google.protobuf.AbstractParser<VehiclePVT>() {
      @Override
      public VehiclePVT parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new VehiclePVT(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<VehiclePVT> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<VehiclePVT> getParserForType() {
      return PARSER;
    }

    @Override
    public com.dpi.map.cabin.domain.proto.DpiMeOutput.VehiclePVT getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dpi_comm_mapengine_CPoint6D_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dpi_comm_mapengine_CPoint6D_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dpi_comm_mapengine_PositionMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dpi_comm_mapengine_PositionMsg_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dpi_comm_mapengine_VehiclePVT_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dpi_comm_mapengine_VehiclePVT_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\023dpi_me_output.proto\022\022dpi.comm.mapengin" +
      "e\"U\n\010CPoint6D\022\t\n\001x\030\001 \001(\001\022\t\n\001y\030\002 \001(\001\022\t\n\001z" +
      "\030\003 \001(\001\022\013\n\003yaw\030\004 \001(\002\022\r\n\005pitch\030\005 \001(\002\022\014\n\004ro" +
      "ll\030\006 \001(\002\"r\n\013PositionMsg\022\r\n\005msgId\030\001 \001(\r\022\017" +
      "\n\007msgType\030\002 \001(\t\022\017\n\007msgTime\030\003 \001(\004\0222\n\nvehi" +
      "clePos\030\004 \001(\0132\036.com.dpi.map.cabin.domain.proto.Vehicl" +
      "ePVT\"l\n\nVehiclePVT\022\014\n\004time\030\001 \001(\004\022-\n\007poin" +
      "t6D\030\002 \001(\0132\034.com.dpi.map.cabin.domain.proto.CPoint6D\022" +
      "\r\n\005speed\030\003 \001(\001\022\022\n\nconfidence\030\004 \001(\rB\002H\003b\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_dpi_comm_mapengine_CPoint6D_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dpi_comm_mapengine_CPoint6D_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dpi_comm_mapengine_CPoint6D_descriptor,
        new String[] { "X", "Y", "Z", "Yaw", "Pitch", "Roll", });
    internal_static_dpi_comm_mapengine_PositionMsg_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_dpi_comm_mapengine_PositionMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dpi_comm_mapengine_PositionMsg_descriptor,
        new String[] { "MsgId", "MsgType", "MsgTime", "VehiclePos", });
    internal_static_dpi_comm_mapengine_VehiclePVT_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_dpi_comm_mapengine_VehiclePVT_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dpi_comm_mapengine_VehiclePVT_descriptor,
        new String[] { "Time", "Point6D", "Speed", "Confidence", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
